// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("thirtytwo_tests")]

[assembly: SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "By design.")]
[assembly: SuppressMessage(
    "Interoperability",
    "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time",
    Justification = "Not possible as types generated by CsWin32 cannot be used by another generator.")]