// Copyright (c) Jeremy W. Kuhne. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.ButtonControl.Styles")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "member", Target = "~F:Windows.FontWeight.Black")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.FontWeight")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.SystemColor")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.StockBrush")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.ExtendedWindowStyles")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.DrawTextFormat")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.IconId")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.MessageBoxStyles")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.WindowStyles")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.VirtualKey")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "Matches Windows", Scope = "type", Target = "~T:Windows.Win32.Graphics.GdiPlus.PixelFormat")]
[assembly: SuppressMessage("Usage", "CA2231:Overload operator equals on overriding value type Equals", Justification = "CsWin32", Scope = "type", Target = "~T:Windows.Win32.Foundation.PCWSTR")]
[assembly: SuppressMessage("Naming", "TOUKI0041:Naming rule violation", Justification = "Mirrors the native IManagedObject interface shape.", Scope = "type", Target = "~T:Windows.DotNet.IManagedObject.Interface")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`1")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`2")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`3")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`4")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`5")]
[assembly: SuppressMessage("Maintainability", "TOUKI0020:Declare one type per file", Justification = "Generic arities intentionally share one conceptual interface family.", Scope = "type", Target = "~T:Windows.Win32.System.Com.IManagedWrapper`6")]